modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/fox-lol/cats-plus/issues"
license = "GPL-3.0"

[[mods]]
    modId = "catsplus"
    version = "${version}"
    displayName = "Cats Plus"
    displayURL = "https://github.com/fox-lol/cats-plus"
    authors = "Foxkin, Insertish, Lutitious, ShaksterNano"
    description = '''
    A funny mod about funny cats :D
    '''
    logoFile = "icon.png"

[[dependencies.catsplus]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.catsplus]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.catsplus]]
    modId = "architectury"
    mandatory = true
    versionRange = "[4.9.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.catsplus]]
    modId = "cloth_config"
    mandatory = true
    versionRange = "[6.4.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.catsplus]]
    modId = "noteblocklib"
    mandatory = true
    versionRange = "[1.0.0,)"
    ordering = "AFTER"
    side = "BOTH"
