name: Build
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  gradle:
    strategy:
      matrix:
        image: [ ubuntu-latest ]
        java: [
          17, # Java LTS, required by Minecraft 1.19
        ]

    runs-on: ${{ matrix.image }}
    name: Build for Java ${{ matrix.java }} on ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Generate sources
      run: ./gradlew genSourcesWithQuiltflower

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Upload build artifacts
      if: ${{ matrix.image == 'ubuntu-latest' && matrix.java == '17' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            common/build/libs/
            fabric/build/libs/
            forge/build/libs/
